name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            # 1. 경로 이동
            cd ~/aemp-playauto

            # 2. 최신 소스 가져오기
            git fetch --all
            git reset --hard origin/main

            # 3. 프론트엔드 빌드
            cd frontend
            npm install
            npm run build
            cd ..

            # 4. 백엔드 + DB 도커만 재시작
            docker compose stop
            docker compose up -d --build playauto-db aemp-playauto-backend

            # 5. Nginx reload (dist 파일 경로 변경 반영)
            sudo systemctl reload nginx
          EOF
