name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
        ssh-known-hosts: ${{ secrets.EC2_HOST }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.66.23.6 << 'EOF'
          set -e  # ⬅️ 중간에 하나라도 에러나면 ssh 연결 종료시킴
          cd ~/aemp-playauto

          echo "✅ GIT PULL"
          git fetch --all
          git reset --hard origin/main

          echo "✅ Frontend Build"
          cd ~/aemp-playauto/frontend
          npm install
          npm run build
          sudo chmod -R 755 ~/aemp-playauto/frontend/dist

          echo "✅ Backend Docker Restart"
          cd ~/aemp-playauto  # docker-compose 있는 폴더로 다시 이동
          sudo docker-compose down
          sudo docker-compose up -d --build
        EOF
